import { Role } from '../types';

export const PERMISSIONS: Record<Role, string[]> = {
  STUDENT: [
    'lesson:view',
    'lesson:progress',
    'activity:view',
    'activity:submit',
    'quiz:attempt',
    'comment:create',
    'material:download',
    'certificate:view',
    'calendar:view',
    'announcement:view',
  ],
  INSTRUCTOR: [
    'lesson:view',
    'lesson:edit',
    'lesson:progress',
    'activity:view',
    'activity:grade',
    'activity:create',
    'quiz:attempt',
    'comment:create',
    'comment:pin',
    'comment:delete',
    'announcement:create',
    'note:create',
    'note:view',
    'material:upload',
    'material:download',
    'material:manage',
    'student:view_progress',
    'certificate:issue',
    'calendar:manage',
  ],
  ADMIN: [
    'lesson:view',
    'lesson:edit',
    'lesson:create',
    'lesson:delete',
    'course:manage',
    'classroom:manage',
    'user:manage',
    'report:view',
    'activity:grade',
    'activity:create',
    'announcement:create',
    'note:create',
    'note:view',
    'material:upload',
    'material:manage',
    'certificate:issue',
    'certificate:manage',
    'audit:view',
    'calendar:manage',
  ],
  SUPER_ADMIN: [
    'organization:manage',
    'settings:manage',
    'lesson:view',
    'lesson:edit',
    'lesson:create',
    'lesson:delete',
    'course:manage',
    'classroom:manage',
    'user:manage',
    'report:view',
    'activity:grade',
    'activity:create',
    'announcement:create',
    'note:create',
    'note:view',
    'material:upload',
    'material:manage',
    'certificate:issue',
    'certificate:manage',
    'audit:view',
    'calendar:manage',
  ],
};

export function hasPermission(role: Role, action: string): boolean {
  const allowed = PERMISSIONS[role] || [];
  if (role === 'SUPER_ADMIN') return true;
  return allowed.includes(action);
}

export const ROLE_LABELS: Record<Role, { label: string; badge: string; color: string; description: string }> = {
  STUDENT: {
    label: 'Aluno / Recruta',
    badge: 'Aluno',
    color: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
    description: 'Acesso a aulas matriculadas, envio de atividades, materiais e certificados',
  },
  INSTRUCTOR: {
    label: 'Instrutor / Oficial',
    badge: 'Instrutor',
    color: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    description: 'Gestão pedagógica, correção de atividades, anotações de prontuário e comunicados',
  },
  ADMIN: {
    label: 'Coordenação / Admin',
    badge: 'Coordenação',
    color: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
    description: 'Gerenciamento de cursos, turmas, matrículas, relatórios e auditoria',
  },
  SUPER_ADMIN: {
    label: 'Comando Geral',
    badge: 'Comandante',
    color: 'bg-red-500/10 text-red-400 border-red-500/20',
    description: 'Acesso irrestrito a configurações institucionais e todos os módulos do LMS',
  },
};
